import_announcements_from_outside_dot_in:
    cron: "0 * * * *"
    class: AnnouncementImporter
    args: 
    queue: outside-data
    description: "This job imports relevant posts from outside.in as Announcements"
import_events_from_eventful:
    cron: "0 * * * *"
    class: EventfulImporter
    args: 
    queue: outside-data
    description: "This job imports events from Eventful into each community as Events"